<div id="<?= $item_id ?>" class="form-group form-actions collapsible-item">
    <div class="collapsible-title">
        <h3 data-id="collapsible-title" onclick="toggleCollapsible('<?= $item_id ?>')" type="button"
            class="collapsible">
            <?= $item['title'] ?>
        </h3>
        <a data-id="delete-item" class="<?= $index == 0 ? "hidden" : '' ?>"
            onclick="removeItem('<?= $item_id ?>')">
            <img class="icon delete-item-icon" src="../themes/icons/close.svg" loading="lazy" alt="❌">
        </a>
    </div>

    <div class="collapsible-content">
        <?php include 'webhook-form.partial.phtml'; ?>
    </div>
</div>