<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <div class="form-group">
        <label for="webhookUrl" class="group-name">Webhook URL</label>
        <div class="group-controls">
            <input type="text" name="webhookUrl" id="webhookUrl" value="<?= $this->getWebhookURL() ?>" />
        </div>
    </div>

    <div class="form-group">
        <label for="username" class="group-name">Username</label>
        <div class="group-controls">
            <input type="text" name="username" id="username" value="<?= $this->getUsername() ?>" />
        </div>
    </div>

    <div class="form-group">
        <label for="color" class="group-name">Embed Color</label>
        <div class="group-controls">
            <input type="color" name="color" id="color" value="<?= $this->getColor() ?>" />
        </div>
    </div>

    <div class="form-group">
        <label for="avatar" class="group-name">Avatar URL</label>
        <div class="group-controls">
            <input type="text" name="avatar" id="avatar" value="<?= $this->getAvatar() ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="avatar-preview" class="group-name">Avatar Preview</label>
        <div class="group-controls">
            <img
                alt="Avatar Preview"
                id="avatar-preview"
                style="object-fit: contain; width: 100px; height: 100px;"
                src="<?= $this->getAvatar() ?>"
            />
        </div>
    </div>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important">Save</button>
            <button type="reset" class="btn">Cancel</button>
        </div>
    </div>
</form>
