<form id="extention-form" action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
    <input type="hidden" name="discord-notifications-data" value="[]" />
    <div id="new-version"></div>
    <div class="discord-notifications-list">
        <?php
        $data = $this->getData();

        foreach ($data as $index => $item) {
            $item_id = "collapsible-{$index}";
            include 'partials/collapsible.partial.phtml';
        } ?>
    </div>

    <button type="button" class="btn btn-important add-btn" onclick="addNotificationItem()">
        Add Notification
    </button>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button id="save-changes" type="submit" class="btn btn-important">Save</button>
            <a type="reset" class="btn" href="#" role="button">Cancel</a>
        </div>
    </div>
</form>